name: malariagen-21ca02e
channels:
  - conda-forge
  - bioconda
  - defaults
  - conda-forge/label/broken
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - adal=1.2.2=py_0
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h516909a_0
  - alembic=1.3.2=py_0
  - appdirs=1.4.3=py_1
  - asciitree=0.3.3=py_2
  - asteval=0.9.16=pyh5ca1d4c_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bcftools=1.9=h68d8f2e_9
  - bcolz=1.2.1=py37hb3f55d8_1001
  - bcrypt=3.1.7=py37h516909a_0
  - biopython=1.76=py37h516909a_0
  - blas=2.14=openblas
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - blosc=1.17.0=he1b5a44_1
  - bokeh=1.4.0=py37_0
  - boto3=1.11.3=py_0
  - botocore=1.14.3=py_0
  - bqplot=0.12.2=py_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hfb77d84_1002
  - cartopy=0.17.0=py37h423102d_1009
  - certifi=2019.11.28=py37_0
  - certipy=0.1.3=py_0
  - cffi=1.13.2=py37h8022711_0
  - cftime=1.0.4.2=py37hc1659b7_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_1
  - configargparse=0.13.0=py_1
  - configurable-http-proxy=4.2.0=node13_he01fd0c_2
  - cryptography=2.8=py37h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cython=0.29.14=py37he1b5a44_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2.9.0=py_0
  - dask-core=2.9.0=py_0
  - dask-glm=0.2.0=py_1
  - dask-kubernetes=0.10.0=py_0
  - dask-ml=1.2.0=py_0
  - datrie=0.8=py37h516909a_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.9.0=py_0
  - docutils=0.15.2=py37_0
  - dropbox=9.4.0=py_0
  - entrypoints=0.3=py37_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.5=he1b5a44_1004
  - fastcluster=1.1.25=py37hb3f55d8_1000
  - fasteners=0.14.1=py_3
  - fastparquet=0.3.2=py37hc1659b7_0
  - fftw=3.3.8=nompi_h7f3a6c3_1110
  - filechunkio=1.8=py_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=2.001=hab24e00_0
  - font-ttf-source-code-pro=2.030=hab24e00_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - fonts-conda-forge=1=0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - fsspec=0.6.2=py_0
  - ftputil=3.4=py_0
  - fusepy=3.0.1=py_0
  - gcsfs=0.6.0=py_0
  - gdk-pixbuf=2.36.12=h3f25603_1005
  - geos=3.8.0=he1b5a44_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - ghostscript=9.22=hf484d3e_1001
  - giflib=5.2.1=h516909a_1
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.5=py_0
  - glib=2.58.3=py37h6f030ca_1002
  - gobject-introspection=1.58.2=py37h5503ade_1002
  - google-api-core=1.16.0=py37_1
  - google-auth=1.10.0=py_1
  - google-auth-oauthlib=0.4.1=py_1
  - google-cloud-core=1.1.0=py_1
  - google-cloud-storage=1.24.1=py37_1
  - google-resumable-media=0.5.0=py_1
  - googleapis-common-protos=1.6.0=py37_1
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.42.3=h0511662_0
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py37h513d04c_101
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - hmmlearn=0.2.3=py37hc1659b7_0
  - holoviews=1.12.7=py_0
  - htslib=1.9=h244ad75_9
  - humanize=0.5.1=py_1
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - imageio=2.6.1=py37_0
  - imagemagick=7.0.9_16=pl526ha9fe49d_0
  - importlib_metadata=1.4.0=py37_0
  - intake=0.5.4=py_0
  - intake-xarray=0.3.1=py_0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipyleaflet=0.12.0=py37_0
  - ipython=7.9.0=py36h5ca1d4c_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jbig=2.1=h14c3975_2001
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.4=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.6.1=py37_0
  - jupyterhub=1.0.0=py37_0
  - jupyterlab=1.2.4=py_0
  - jupyterlab_launcher=0.13.1=py_2
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - kubernetes_asyncio=10.0.1=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcroco=0.6.13=h8d621e5_0
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.3=h516909a_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_4
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm8=8.0.1=hc9558a2_0
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.7.3=nompi_h94020b1_100
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.11.2=h8b12597_0
  - librsvg=2.46.4=h33a7fed_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.31.0=py37h8b12597_0
  - lmfit=1.0.0=py_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py37h516909a_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h250f245_1
  - matplotlib-venn=0.11.5=py_1
  - mistune=0.8.4=py37h516909a_1000
  - monotonic=1.5=py_0
  - more-itertools=8.1.0=py_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.6.2=py37hc9558a2_0
  - msprime=0.7.4=py37heade8f8_0
  - multidict=4.7.3=py37h516909a_0
  - multipledispatch=0.6.0=py_0
  - mysql-connector-c=6.1.11=hd2bbab6_1004
  - mysqlclient=1.4.6=py37he1b5a44_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - nbserverproxy=0.8.8=py_1000
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.3=nompi_py37hd35fb8e_102
  - networkx=2.4=py_0
  - nodejs=13.6.0=h10a4023_0
  - nose=1.3.7=py37_1003
  - notebook=6.0.1=py37_0
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.47.0=py37hb3f55d8_0
  - numcodecs=0.6.4=py37he1b5a44_0
  - numexpr=2.7.1=py37hb3f55d8_0
  - numpy=1.17.3=py37h95a1406_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1d=h516909a_0
  - owslib=0.19.0=py_2
  - packaging=20.0=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.3=py37hb3f55d8_0
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - param=1.9.2=py_0
  - paramiko=2.7.1=py37_0
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - peakutils=1.3.2=py_0
  - perl=5.26.2=h516909a_1006
  - petl=1.3.0=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=7.0.0=py37hefe7db6_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - pomegranate=0.12.0=py37hc9558a2_0
  - prettytable=0.7.2=py_3
  - proj=6.2.1=hc80f0dc_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.11.2=py37he1b5a44_0
  - psutil=5.6.7=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py37_1
  - pycurl=7.43.0.4=py37h16ce93b_0
  - pyepsg=0.4.0=py_0
  - pyfaidx=0.5.7=py_0
  - pyfasta=0.5.2=py_1
  - pygments=2.5.2=py_0
  - pygraphviz=1.3=py37h14c3975_1
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py37hc1659b7_1002
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.4.2.post1=py37h12732c1_0
  - pyqt=5.12.3=py37hcca6a23_1
  - pyrsistent=0.15.7=py37h516909a_0
  - pysam=0.15.3=py37hbcae180_3
  - pysamstats=1.1.2=py37hed695b0_5
  - pysftp=0.2.9=py_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - pytables=3.6.1=py37h9f153d1_0
  - python=3.7.6=h357f687_2
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python-graphviz=0.13.2=py_0
  - python-irodsclient=0.7.0=py_0
  - python-kubernetes=10.0.1=py37_0
  - python-snappy=0.5.4=py37hee44bf9_1
  - pytz=2019.3=py_0
  - pyvcf=0.6.8=py37_1000
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyyaml=5.3=py37h516909a_0
  - pyzmq=18.1.1=py37h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.6.0=py_0
  - ratelimiter=1.2.0=py37_1000
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - requests-oauthlib=1.2.0=py_0
  - rsa=4.0=py_0
  - ruamel.yaml=0.16.5=py37h516909a_1
  - ruamel.yaml.clib=0.2.0=py37h516909a_0
  - s3fs=0.4.0=py_0
  - s3transfer=0.3.0=py37_0
  - samtools=1.9=h10a08f8_12
  - scikit-allel=1.2.1=py37hb3f55d8_1
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scikit-learn=0.22.1=py37hcdab131_1
  - scipy=1.4.1=py37h921218d_0
  - seaborn=0.9.0=py_2
  - send2trash=1.5.0=py_0
  - setuptools=45.0.0=py37_1
  - shapely=1.6.4=py37h5d51c17_1007
  - six=1.14.0=py37_0
  - smmap2=2.0.5=py_0
  - snakemake=5.9.1=0
  - snakemake-minimal=5.9.1=py_0
  - snappy=1.1.7=he1b5a44_1003
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.12=py37h516909a_0
  - sqlite=3.30.1=hcee41ef_0
  - statsmodels=0.10.2=py37hc1659b7_0
  - svgwrite=1.3.1=py_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - thrift=0.11.0=py37he1b5a44_1001
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - traitlets=4.3.3=py37_0
  - traittypes=0.2.1=py_1
  - tskit=0.2.3=py37hc1659b7_0
  - umap-learn=0.3.10=py37_1
  - uncertainties=3.1.3=py_0
  - urllib3=1.25.7=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py37_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xarray=0.14.1=py_1
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - yarl=1.3.0=py37h516909a_1000
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zipp=1.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - alabaster==0.7.12
    - anhima==0.11.2
    - argcomplete==1.11.1
    - argh==0.26.2
    - babel==2.8.0
    - boto==2.49.0
    - cached-property==1.5.1
    - crcmod==1.7
    - gcs-oauth2-boto-plugin==2.5
    - google-apitools==0.5.30
    - google-reauth==0.1.0
    - gsutil==4.47
    - httplib2==0.16.0
    - imagesize==1.2.0
    - livereload==2.6.1
    - mock==2.0.0
    - oauth2client==4.1.3
    - pathtools==0.1.2
    - pbr==5.4.4
    - petlx==1.0.3
    - port-for==0.3.1
    - prettypandas==0.0.4
    - pyerf==1.0.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyu2f==0.1.4
    - retry-decorator==1.1.0
    - scikits-bootstrap==1.0.1
    - snowballstemmer==2.0.0
    - socksipy-branch==1.1
    - sphinx==2.3.1
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.7.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - watchdog==0.9.0
