name: malariagen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - adal=1.2.2=py_0
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.5.4=py36h14c3975_0
  - alembic=1.1.0=py_0
  - appdirs=1.4.3=py_1
  - asciitree=0.3.3=py_2
  - asn1crypto=0.24.0=py36_1003
  - asteval=0.9.14=pyh24bf2e0_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bcftools=1.9=h5c2b69b_5
  - bcolz=1.2.1=py36h637b7d7_1001
  - bcrypt=3.1.6=py36h516909a_1
  - biopython=1.74=py36h516909a_0
  - blas=2.12=openblas
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - blosc=1.17.0=he1b5a44_1
  - bokeh=1.3.4=py36_0
  - boto3=1.9.216=py_0
  - botocore=1.12.216=py_0
  - bqplot=0.11.7=py_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.16.0=hfb77d84_1002
  - cartopy=0.17.0=py36h4331854_1006
  - certifi=2019.6.16=py36_1
  - certipy=0.1.3=py_0
  - cffi=1.12.3=py36h8022711_0
  - cftime=1.0.3.4=py36hd352d35_1001
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - cloudpickle=1.2.1=py_0
  - configargparse=0.13.0=py_1
  - configurable-http-proxy=4.1.0=node11_1
  - cryptography=2.7=py36h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_1
  - cython=0.29.13=py36he1b5a44_0
  - cytoolz=0.10.0=py36h516909a_0
  - dask=2.3.0=py_0
  - dask-core=2.3.0=py_0
  - dask-glm=0.1.0=0
  - dask-kubernetes=0.9.2=py_0
  - dask-ml=1.0.0=py_0
  - datrie=0.8=py36h516909a_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - distributed=2.3.2=py_1
  - docutils=0.15.2=py36_0
  - dropbox=9.4.0=py_0
  - entrypoints=0.3=py36_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.5=he1b5a44_1003
  - fastcluster=1.1.25=py36h637b7d7_1000
  - fasteners=0.14.1=py_3
  - fastparquet=0.3.2=py36hc1659b7_0
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fsspec=0.4.1=py_0
  - ftputil=3.4=py_0
  - fusepy=3.0.1=py_0
  - gcsfs=0.3.0=py_0
  - geos=3.7.2=he1b5a44_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - gitdb2=2.0.5=py_0
  - gitpython=3.0.2=py_0
  - glib=2.58.3=h6f030ca_1002
  - google-api-core=1.14.2=py36_0
  - google-auth=1.6.3=py_0
  - google-auth-oauthlib=0.4.0=py_0
  - google-cloud-core=1.0.3=py_0
  - google-cloud-storage=1.18.0=py_0
  - google-resumable-media=0.3.2=py_0
  - googleapis-common-protos=1.6.0=py36_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.38.0=hf68f40c_1011
  - gsl=2.5=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=nompi_py36h513d04c_1104
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=h9a582f1_1002
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - heapdict=1.0.0=py36_1000
  - hmmlearn=0.2.1=py36h3010b51_1000
  - holoviews=1.12.5=py_0
  - htslib=1.9=ha228f0b_7
  - humanize=0.5.1=py_1
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - imageio=2.5.0=py36_0
  - intake=0.5.3=py_0
  - intake-xarray=0.3.1=py_0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.2=py36h5ca1d4c_0
  - ipyleaflet=0.11.1=py36_1
  - ipython=7.7.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.1=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterhub=1.0.0=py36_0
  - jupyterlab=1.0.9=py36_0
  - jupyterlab_launcher=0.13.1=py_2
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - liblapacke=3.8.0=12_openblas
  - libnetcdf=4.6.2=h056eaf5_1002
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.1=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - llvmlite=0.29.0=py36hfd453ef_1
  - lmfit=0.9.13=pyh24bf2e0_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - lzo=2.10=h14c3975_1000
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36he7580a8_1
  - matplotlib-venn=0.11.5=py_1
  - mistune=0.8.4=py36h14c3975_1000
  - mock=3.0.5=py36_0
  - monotonic=1.5=py_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - msprime=0.7.3=py36heade8f8_0
  - multidict=4.5.2=py36h14c3975_1000
  - multipledispatch=0.6.0=py_0
  - mysql-connector-c=6.1.11=hd2bbab6_1003
  - mysqlclient=1.4.3=py36he1b5a44_0
  - nb_conda_kernels=2.2.2=py36_0
  - nbconvert=5.6.0=py_0
  - nbformat=4.4.0=py_1
  - nbserverproxy=0.8.8=py_1000
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.1.2=py36h73a1b54_1
  - networkx=2.3=py_0
  - nodejs=11.14.0=he1b5a44_1
  - nose=1.3.7=py36_1002
  - notebook=6.0.1=py36_0
  - numba=0.45.1=py36hb3f55d8_0
  - numcodecs=0.6.3=py36hf484d3e_0
  - numexpr=2.7.0=py36hb3f55d8_0
  - numpy=1.17.1=py36h95a1406_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openpyxl=2.6.3=py_0
  - openssl=1.1.1c=h516909a_0
  - owslib=0.18.0=py_0
  - packaging=19.0=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.1=py36hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=he7ab937_1005
  - param=1.9.1=py_0
  - paramiko=2.6.0=py36_0
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - petl=1.3.0=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pillow=6.1.0=py36h6b7be26_1
  - pip=19.2.3=py36_0
  - pixman=0.38.0=h516909a_1003
  - pomegranate=0.11.0=py36h9de70de_0
  - prettytable=0.7.2=py_3
  - proj4=6.1.1=hc80f0dc_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.9.1=py36he1b5a44_0
  - psutil=5.6.3=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.6=py_0
  - pyasn1-modules=0.2.6=py_0
  - pycparser=2.19=py36_1
  - pycurl=7.43.0.2=py36h16ce93b_1
  - pyepsg=0.4.0=py_0
  - pyfaidx=0.5.5.2=py_1
  - pyfasta=0.5.2=py36_0
  - pygments=2.4.2=py_0
  - pygraphviz=1.5=py36h516909a_1001
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py36h3010b51_1002
  - pynacl=1.3.0=py36h14c3975_1000
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.2=py_0
  - pyproj=2.3.0=py36h2fd02e8_0
  - pyqt=5.9.2=py36hcca6a23_2
  - pyrsistent=0.15.4=py36h516909a_0
  - pysam=0.15.3=py36hda2845c_1
  - pysamstats=1.1.2=py36h84994c4_3
  - pysftp=0.2.9=py_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py36_0
  - pytables=3.5.2=py36h9f153d1_2
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - python-graphviz=0.12=py_0
  - python-irodsclient=0.7.0=py_0
  - python-kubernetes=10.0.1=py36_0
  - python-snappy=0.5.4=py36hee44bf9_0
  - pytz=2019.2=py_0
  - pyvcf=0.6.8=py36_1000
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.0.3=py36hd352d35_1
  - pyyaml=5.1.2=py36h516909a_0
  - pyzmq=18.0.2=py36h1768529_2
  - qt=5.9.7=h0c104cb_3
  - qtconsole=4.5.4=py_0
  - ratelimiter=1.2.0=py36_1000
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py36_1
  - requests-oauthlib=1.2.0=py_0
  - rsa=3.4.2=py_1
  - ruamel.yaml=0.16.5=py36h516909a_1
  - ruamel.yaml.clib=0.1.2=py36h516909a_0
  - s3fs=0.3.3=py_0
  - s3transfer=0.2.1=py36_0
  - samtools=1.9=h8571acd_11
  - scikit-allel=1.2.1=py36hb3f55d8_0
  - scikit-image=0.15.0=py36hb3f55d8_2
  - scikit-learn=0.21.3=py36hcdab131_0
  - scipy=1.3.1=py36h921218d_2
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py36_0
  - shapely=1.6.4=py36hec07ddf_1006
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - smmap2=2.0.5=py_0
  - snakemake=5.5.4=1
  - snakemake-minimal=5.5.4=py_1
  - snappy=1.1.7=he1b5a44_1002
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.7=py36h516909a_0
  - sqlite=3.29.0=hcee41ef_0
  - statsmodels=0.10.1=py36hc1659b7_0
  - svgwrite=1.3.1=py_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - thrift=0.11.0=py36hf484d3e_1001
  - tk=8.6.9=hed695b0_1002
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - traittypes=0.2.1=py_1
  - tskit=0.2.1=py36hc1659b7_0
  - typing_extensions=3.7.4=py36_0
  - uncertainties=3.1.2=py36_0
  - urllib3=1.25.3=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - websocket-client=0.56.0=py36_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h516909a_0
  - xarray=0.12.3=py_0
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py36h14c3975_1000
  - zarr=2.3.2=py36_0
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - alabaster==0.7.12
    - anhima==0.11.2
    - argh==0.26.2
    - babel==2.7.0
    - cached-property==1.5.1
    - imagesize==1.1.0
    - livereload==2.6.1
    - pathtools==0.1.2
    - petlx==1.0.3
    - port-for==0.3.1
    - prettypandas==0.0.4
    - scikits-bootstrap==0.3.3
    - snowballstemmer==1.9.0
    - sphinx==2.2.0
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.7.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - watchdog==0.9.0
