name: malariagen-7cdc088
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adal=1.2.2=py_0
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.6.1=py36h01d97ff_0
  - alembic=1.3.0=py_0
  - appdirs=1.4.3=py_1
  - appnope=0.1.0=py36_1000
  - asciitree=0.3.3=py_2
  - asteval=0.9.16=pyh5ca1d4c_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bcftools=1.9=h16e57c4_8
  - bcolz=1.2.1=py36h4f17bb1_1001
  - bcrypt=3.1.7=py36h0b31af3_0
  - biopython=1.74=py36h0b31af3_0
  - blas=2.14=openblas
  - bleach=3.1.0=py_0
  - blinker=1.4=py_1
  - blosc=1.17.0=h6de7cb9_1
  - bokeh=1.3.4=py36_0
  - boto3=1.10.12=py_0
  - botocore=1.13.12=py_0
  - bqplot=0.12.0=py_0
  - branca=0.3.1=py_0
  - bzip2=1.0.8=h01d97ff_1
  - ca-certificates=2019.9.11=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.16.0=he1c11cd_1002
  - cartopy=0.17.0=py36h95120c7_1007
  - certifi=2019.9.11=py36_0
  - certipy=0.1.3=py_0
  - cffi=1.13.2=py36h33e799b_0
  - cftime=1.0.4.2=py36h3b54f70_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_0
  - configargparse=0.13.0=py_1
  - configurable-http-proxy=1.3.0=0
  - cryptography=2.8=py36hafa8578_0
  - curl=7.65.3=h22ea746_0
  - cycler=0.10.0=py_2
  - cython=0.29.14=py36h4a8c4bd_0
  - cytoolz=0.10.1=py36h0b31af3_0
  - dask=2.6.0=py_0
  - dask-core=2.6.0=py_0
  - dask-glm=0.2.0=py_1
  - dask-kubernetes=0.10.0=py_0
  - dask-ml=1.1.1=py_0
  - datrie=0.8=py36h01d97ff_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.6.0=py_0
  - docutils=0.15.2=py36_0
  - dropbox=9.4.0=py_0
  - entrypoints=0.3=py36_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.5=h4a8c4bd_1004
  - fastcluster=1.1.25=py36h4f17bb1_1000
  - fasteners=0.14.1=py_3
  - fastparquet=0.3.2=py36heacc8b8_0
  - fftw=3.3.8=nompi_h44ae4c8_1110
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.10.0=h24853df_1
  - fribidi=1.0.5=h01d97ff_1002
  - fsspec=0.5.2=py_0
  - ftputil=3.4=py_0
  - fusepy=3.0.1=py_0
  - gcsfs=0.3.1=py_0
  - gdk-pixbuf=2.36.12=h284f8de_1003
  - geos=3.7.2=h6de7cb9_2
  - gettext=0.19.8.1=h46ab8bc_1002
  - ghostscript=9.22=h0a44026_1001
  - giflib=5.1.7=h01d97ff_1
  - gitdb2=2.0.6=py_0
  - gitpython=3.0.4=py_0
  - glib=2.58.3=h9d45998_1002
  - gobject-introspection=1.58.2=py36h93883a9_1002
  - google-api-core=1.14.3=py36_0
  - google-auth=1.6.3=py_0
  - google-auth-oauthlib=0.4.1=py_0
  - google-cloud-core=1.0.3=py_0
  - google-cloud-storage=1.20.0=py_0
  - google-resumable-media=0.4.1=py_0
  - googleapis-common-protos=1.6.0=py36_0
  - graphite2=1.3.13=h2098e52_1000
  - graphviz=2.40.1=h69955ae_1
  - gsl=2.5=ha2d443c_1
  - h5py=2.10.0=nompi_py36h106b333_100
  - harfbuzz=2.4.0=hd8d2a14_3
  - hdf4=4.2.13=hf3c6af0_1002
  - hdf5=1.10.5=nompi_h3e39495_1104
  - heapdict=1.0.1=py_0
  - hmmlearn=0.2.2=py36h3b54f70_0
  - holoviews=1.12.6=py_0
  - htslib=1.9=h356306b_9
  - humanize=0.5.1=py_1
  - icu=64.2=h6de7cb9_1
  - idna_ssl=1.1.0=py36_1000
  - imageio=2.6.1=py36_0
  - imagemagick=7.0.9_2=pl526h1471ef3_0
  - importlib_metadata=0.23=py36_0
  - intake=0.5.3=py_0
  - intake-xarray=0.3.1=py_0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.3=py36h5ca1d4c_0
  - ipyleaflet=0.11.4=py36_1
  - ipython=7.9.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jbig=2.1=h1de35cc_2001
  - jdcal=1.4.1=py_0
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=h1de35cc_1001
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.3=py36_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.5.0=py_0
  - jupyterhub=1.0.0=py36_0
  - jupyterlab=1.2.1=py_0
  - jupyterlab_launcher=0.13.1=py_2
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py36ha1b3eb9_0
  - krb5=1.16.3=hcfa6398_1001
  - kubernetes_asyncio=10.0.0=py_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=8.0.1=h770b8ee_1
  - libcroco=0.6.13=hc484408_0
  - libcurl=7.65.3=h16faf7d_0
  - libcxx=9.0.0=h89e68fa_1
  - libdeflate=1.3=h01d97ff_0
  - libedit=3.1.20170329=hcfe32e1_1001
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - libiconv=1.15=h01d97ff_1005
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm8=8.0.1=h770b8ee_0
  - libnetcdf=4.7.1=nompi_he14bcb6_101
  - libopenblas=0.3.7=h4bb4525_3
  - libpng=1.6.37=h2573ce8_0
  - libprotobuf=3.10.1=hd174df1_0
  - librsvg=2.46.2=h1ccd86b_1
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=h3527a1b_0
  - libuv=1.33.1=h01d97ff_0
  - libwebp=1.0.2=h14d73da_2
  - libxcb=1.13=h1de35cc_1002
  - libxml2=2.9.10=h53d96d6_0
  - llvm-openmp=9.0.0=h40edb58_0
  - llvmlite=0.30.0=py36h05045ef_1
  - lmfit=0.9.14=pyh24bf2e0_0
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=h6de7cb9_1001
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py36h0b31af3_0
  - matplotlib=3.1.2=py36_0
  - matplotlib-base=3.1.2=py36h11da6c2_0
  - matplotlib-venn=0.11.5=py_1
  - mistune=0.8.4=py36h0b31af3_1000
  - monotonic=1.5=py_0
  - more-itertools=7.2.0=py_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.6.2=py36ha1b3eb9_0
  - msprime=0.7.3=py36h1c7146f_1
  - multidict=4.5.2=py36h1de35cc_1000
  - multipledispatch=0.6.0=py_0
  - mysql-connector-c=6.1.11=h42c63d9_1003
  - mysqlclient=1.4.4=py36h4a8c4bd_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py_1
  - nbserverproxy=0.8.8=py_1000
  - ncurses=6.1=h0a44026_1002
  - netcdf4=1.5.3=py36he9269ea_0
  - networkx=2.4=py_0
  - nodejs=12.12.0=hfddbe92_0
  - nose=1.3.7=py36_1003
  - notebook=6.0.1=py36_0
  - nspr=4.20=h0a44026_1000
  - nss=3.47=hcec2283_0
  - numba=0.46.0=py36h4f17bb1_1
  - numcodecs=0.6.3=py36h0a44026_0
  - numexpr=2.7.0=py36h4f17bb1_0
  - numpy=1.17.1=py36h6b0580a_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=hdc36067_1
  - openpyxl=3.0.0=py_0
  - openssl=1.1.1d=h0b31af3_0
  - owslib=0.18.0=py_0
  - packaging=19.2=py_0
  - pamela=1.0.0=py_0
  - pandas=0.25.1=py36h86efe34_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=h6691c8e_1
  - param=1.9.2=py_0
  - paramiko=2.6.0=py36_0
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=h4a8c4bd_0
  - peakutils=1.3.2=py_0
  - perl=5.26.2=haec8ef5_1006
  - petl=1.3.0=py_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pillow=6.2.1=py36hb6f49c9_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h01d97ff_1003
  - pkg-config=0.29.2=h112b980_1005
  - pomegranate=0.11.1=py36hbf1eeb5_0
  - prettytable=0.7.2=py_3
  - proj4=6.1.1=hca663eb_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.10.1=py36h4a8c4bd_0
  - psutil=5.6.5=py36h0b31af3_0
  - pthread-stubs=0.4=h1de35cc_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.7=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.19=py36_1
  - pycurl=7.43.0.3=py36h75a5311_1
  - pyepsg=0.4.0=py_0
  - pyfaidx=0.5.5.2=py_1
  - pyfasta=0.5.2=py_1
  - pygments=2.4.2=py_0
  - pygraphviz=1.3.1=py36_0
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py36h3b54f70_1002
  - pynacl=1.3.0=py36h0b31af3_1001
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.4=py_0
  - pyproj=2.3.1=py36h9bb365a_0
  - pyqt=5.12.3=py36he22c54c_0
  - pyrsistent=0.15.5=py36h0b31af3_0
  - pysam=0.15.3=py36h4ace0ce_3
  - pysamstats=1.1.2=py36h2573ce8_5
  - pysftp=0.2.9=py_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py36_0
  - pytables=3.6.1=py36h6f8395a_0
  - python=3.6.7=h4285619_1006
  - python-dateutil=2.8.0=py_0
  - python-editor=1.0.4=py_0
  - python-graphviz=0.13=py_0
  - python-irodsclient=0.7.0=py_0
  - python-kubernetes=10.0.1=py36_0
  - python-snappy=0.5.4=py36h80de579_1
  - pytz=2019.3=py_0
  - pyvcf=0.6.8=py36_1000
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.1.1=py36h3b54f70_0
  - pyyaml=5.1.2=py36h0b31af3_0
  - pyzmq=18.1.0=py36h4bf09a9_0
  - qt=5.12.5=h1b46049_0
  - qtconsole=4.5.5=py_0
  - ratelimiter=1.2.0=py36_1000
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py36_1
  - requests-oauthlib=1.2.0=py_0
  - rsa=3.4.2=py_1
  - ruamel.yaml=0.16.5=py36h0b31af3_1
  - ruamel.yaml.clib=0.2.0=py36h0b31af3_0
  - s3fs=0.3.5=py_0
  - s3transfer=0.2.1=py36_0
  - samtools=1.9=h8aa4d43_12
  - scikit-allel=1.2.1=py36h86efe34_0
  - scikit-image=0.16.2=py36h4f17bb1_0
  - scikit-learn=0.21.3=py36hd4ffd6c_0
  - scipy=1.3.1=py36h7e0e109_2
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.6.0=py36_1
  - shapely=1.6.4=py36h5c88e11_1006
  - six=1.13.0=py36_0
  - smmap2=2.0.5=py_0
  - snakemake=5.7.4=0
  - snakemake-minimal=5.7.4=py_0
  - snappy=1.1.7=h6de7cb9_1002
  - sortedcontainers=2.1.0=py_0
  - sqlalchemy=1.3.10=py36h0b31af3_0
  - sqlite=3.30.1=h93121df_0
  - statsmodels=0.10.1=py36h3b54f70_1
  - svgwrite=1.3.1=py_0
  - tblib=1.4.0=py_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.4=py_0
  - thrift=0.11.0=py36h4a8c4bd_1001
  - tk=8.6.9=h2573ce8_1003
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h0b31af3_0
  - traitlets=4.3.3=py36_0
  - traittypes=0.2.1=py_1
  - tskit=0.2.2=py36h3b54f70_0
  - typing_extensions=3.7.4.1=py36_0
  - uncertainties=3.1.2=py36_0
  - urllib3=1.25.6=py36_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - websocket-client=0.56.0=py36_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h0b31af3_0
  - xarray=0.14.0=py_0
  - xlrd=1.2.0=py_0
  - xlwt=1.3.0=py_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h1de35cc_1002
  - xorg-libice=1.0.10=h01d97ff_0
  - xorg-libsm=1.2.3=h01d97ff_1000
  - xorg-libx11=1.6.9=h0b31af3_0
  - xorg-libxau=1.0.9=h1de35cc_0
  - xorg-libxdmcp=1.1.3=h01d97ff_0
  - xorg-libxext=1.3.4=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-libxt=1.2.0=h01d97ff_0
  - xorg-renderproto=0.11.1=h1de35cc_1002
  - xorg-xextproto=7.3.0=h1de35cc_1002
  - xorg-xproto=7.0.31=h1de35cc_1007
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - yarl=1.3.0=py36h1de35cc_1000
  - zarr=2.3.2=py36_0
  - zeromq=4.3.2=h6de7cb9_2
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - zstd=1.4.3=he7fca8b_0
  - pip:
    - alabaster==0.7.12
    - anhima==0.11.2
    - argcomplete==1.10.0
    - argh==0.26.2
    - babel==2.7.0
    - boto==2.49.0
    - cached-property==1.5.1
    - crcmod==1.7
    - gcs-oauth2-boto-plugin==2.5
    - google-apitools==0.5.30
    - google-reauth==0.1.0
    - gsutil==4.46
    - httplib2==0.14.0
    - imagesize==1.1.0
    - livereload==2.6.1
    - mock==2.0.0
    - oauth2client==4.1.3
    - pathtools==0.1.2
    - pbr==5.4.3
    - petlx==1.0.3
    - port-for==0.3.1
    - prettypandas==0.0.4
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyu2f==0.1.4
    - retry-decorator==1.1.0
    - scikits-bootstrap==0.3.3
    - snowballstemmer==2.0.0
    - socksipy-branch==1.1
    - sphinx==2.2.1
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.7.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - watchdog==0.9.0