name: malariagen-2805ab9
channels:
  - conda-forge
  - bioconda
  - defaults
  - conda-forge/label/broken
dependencies:
  - adal=1.2.4=pyh9f0ad1d_0
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h0b31af3_0
  - alembic=1.4.2=pyh9f0ad1d_0
  - appdirs=1.4.3=py_1
  - appnope=0.1.0=py37hc8dfbb8_1001
  - asciitree=0.3.3=py_2
  - asteval=0.9.16=pyh5ca1d4c_0
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcftools=1.9=h3a161e8_4
  - bcolz=1.2.1=py37h4f17bb1_1001
  - bcrypt=3.1.7=py37h9bfed18_1
  - biopython=1.77=py37h9bfed18_0
  - blas=2.17=openblas
  - bleach=3.1.5=pyh9f0ad1d_0
  - blinker=1.4=py_1
  - blosc=1.20.0=hb1e8313_0
  - bokeh=2.1.1=py37hc8dfbb8_0
  - boto3=1.14.31=pyh9f0ad1d_0
  - botocore=1.17.31=pyh9f0ad1d_0
  - bqplot=0.12.14=pyh9f0ad1d_0
  - branca=0.3.1=py_0
  - brotli=1.0.7=h4a8c4bd_1004
  - brotlipy=0.7.0=py37h9bfed18_1000
  - bzip2=1.0.8=h0b31af3_2
  - c-ares=1.16.1=haf1e3a3_0
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=hec6a9b0_1003
  - cartopy=0.17.0=py37h8ad5b2f_1015
  - cctools_osx-64=949.0.1=h5ba7a2e_2
  - certifi=2020.6.20=py37hc8dfbb8_0
  - certipy=0.1.3=py_0
  - cffi=1.14.1=py37hf5b7abd_0
  - cftime=1.2.1=py37h5be27a9_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - charls=2.1.0=h4a8c4bd_2
  - clang=10.0.1=default_hf57f61e_0
  - clang_osx-64=10.0.1=h05bbb7f_5
  - clangxx=10.0.1=default_hf57f61e_0
  - clangxx_osx-64=10.0.1=h05bbb7f_5
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.5.0=py_0
  - compiler-rt=10.0.1=he6db49b_0
  - compiler-rt_osx-64=10.0.1=h033240e_0
  - configargparse=1.2.3=pyh9f0ad1d_0
  - configurable-http-proxy=4.2.1=node13_he01fd0c_0
  - crc32c=2.0=py37h0b31af3_0
  - cryptography=3.0=py37h94e4008_0
  - curl=7.71.1=hbdca1c0_4
  - cycler=0.10.0=py_2
  - cython=0.29.21=py37h570ac47_0
  - cytoolz=0.10.1=py37h0b31af3_0
  - dask=2.9.0=py_0
  - dask-core=2.9.0=py_0
  - dask-glm=0.2.0=py_1
  - dask-kubernetes=0.10.1=py_0
  - dask-ml=1.6.0=py_0
  - datrie=0.8.2=py37h9bfed18_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.9.0=py_0
  - docutils=0.15.2=py37_0
  - dropbox=10.1.1=pyh9f0ad1d_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.9=h4a8c4bd_2
  - fastcluster=1.1.26=py37h94625e5_1
  - fasteners=0.14.1=py_3
  - fastparquet=0.4.1=py37h5be27a9_0
  - fftw=3.3.8=mpi_mpich_hd94f463_1011
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=h6b1039f_1001
  - freetype=2.10.2=h8da9a1a_0
  - fsspec=0.7.4=py_0
  - ftputil=4.0.0=py_0
  - fusepy=3.0.1=py_0
  - future=0.18.2=py37hc8dfbb8_1
  - gcsfs=0.6.2=py_0
  - gdk-pixbuf=2.36.12=h306395f_1005
  - geos=3.8.1=h4a8c4bd_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - gfortran_impl_osx-64=7.5.0=h970e067_1
  - gfortran_osx-64=7.5.0=h22b1bf0_4
  - ghostscript=9.22=h0a44026_1001
  - giflib=5.1.7=h01d97ff_1
  - gitdb=4.0.5=py_0
  - gitpython=3.1.3=py_0
  - glib=2.65.0=h577aef8_0
  - gmp=6.2.0=h4a8c4bd_2
  - gobject-introspection=1.64.1=py37hed9d58a_1
  - google-api-core=1.22.0=py37hc8dfbb8_1
  - google-api-python-client=1.10.0=pyh9f0ad1d_0
  - google-auth=1.20.0=py_0
  - google-auth-httplib2=0.0.3=py_3
  - google-auth-oauthlib=0.4.1=py_2
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.30.0=pyh9f0ad1d_0
  - google-crc32c=0.1.0=py37h01f6f9a_1
  - google-resumable-media=0.7.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.51.0=py37hc8dfbb8_2
  - graphite2=1.3.13=h12caacf_1001
  - graphviz=2.38.0=hc6cc99f_1011
  - gsl=2.6=ha2d443c_0
  - h5py=2.10.0=nompi_py37h28defc4_104
  - harfbuzz=2.4.0=hd8d2a14_3
  - hdf4=4.2.13=h84186c3_1003
  - hdf5=1.10.6=nompi_h3e39495_100
  - heapdict=1.0.1=py_0
  - hmmlearn=0.2.3=py37h3b54f70_1
  - holoviews=1.13.3=pyh9f0ad1d_0
  - htslib=1.9=h3a161e8_7
  - httplib2=0.18.1=pyh9f0ad1d_0
  - humanize=2.5.0=py_0
  - icu=64.2=h6de7cb9_1
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py37hec285a2_1
  - imageio=2.9.0=py_0
  - imagemagick=7.0.8_54=pl526h65d2115_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - intake=0.6.0=py_0
  - intake-xarray=0.3.1=py_0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.3.4=py37h43977f1_0
  - ipyleaflet=0.13.3=pyh9f0ad1d_0
  - ipython=7.16.1=py37h43977f1_0
  - ipython_genutils=0.2.0=py_1
  - ipytree=0.1.8=py_0
  - ipywidgets=7.5.1=py_0
  - isl=0.22.1=h65ac59c_1
  - jbig=2.1=h0b31af3_2002
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h0b31af3_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.6=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterhub=1.0.0=py37_0
  - jupyterlab=2.2.2=py_0
  - jupyterlab_launcher=0.13.1=py_2
  - jupyterlab_server=1.2.0=py_0
  - jxrlib=1.1=h0b31af3_2
  - kiwisolver=1.2.0=py37ha1cc60f_0
  - krb5=1.17.1=h14dd6a4_2
  - kubernetes_asyncio=11.3.0=pyh9f0ad1d_0
  - lcms2=2.11=h174193d_0
  - ld64_osx-64=530=h3c32e8a_2
  - libaec=1.0.4=h4a8c4bd_1
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang-cpp10=10.0.1=default_hf57f61e_0
  - libcrc32c=1.1.1=hb1e8313_2
  - libcroco=0.6.13=h9035b8d_1
  - libcurl=7.71.1=he6690cf_4
  - libcxx=10.0.1=h5f48129_0
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20191231=hed1e85f_1
  - libev=4.33=haf1e3a3_0
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - libiconv=1.15=h0b31af3_1006
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm10=10.0.1=h009f743_0
  - libllvm9=9.0.1=h7475705_1
  - libnetcdf=4.7.4=nompi_hc5b2cf3_105
  - libnghttp2=1.41.0=h8a08a2b_1
  - libopenblas=0.3.10=openmp_h63d9170_4
  - libpng=1.6.37=hbbe82c9_1
  - libprotobuf=3.12.3=hab81aa3_2
  - librsvg=2.44.14=h423af4f_0
  - libsodium=1.0.17=h01d97ff_0
  - libssh2=1.9.0=h39bdce6_5
  - libtiff=4.1.0=ha78913b_3
  - libuv=1.34.0=h0b31af3_0
  - libwebp=1.0.2=h20df551_3
  - libxcb=1.13=h1de35cc_1002
  - libxml2=2.9.10=h53d96d6_0
  - libzopfli=1.0.3=h4a8c4bd_0
  - llvm-openmp=10.0.1=h28b9765_0
  - llvm-tools=10.0.1=h1341992_0
  - llvmlite=0.33.0=py37h3986384_1
  - lmfit=1.0.0=py_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=h4a8c4bd_1
  - mako=1.1.3=pyh9f0ad1d_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py37h9bfed18_1
  - matplotlib=3.3.0=1
  - matplotlib-base=3.3.0=py37h886f89f_1
  - matplotlib-venn=0.11.5=py_2
  - mistune=0.8.4=py37h9bfed18_1001
  - monotonic=1.5=py_0
  - mpc=1.1.0=h4160ff4_1007
  - mpfr=4.0.2=h65ac59c_1
  - mpi=1.0=mpich
  - mpich=3.3.2=hc856adb_0
  - msgpack-python=0.6.2=py37ha1b3eb9_0
  - msprime=0.7.4=py37h4caa599_1
  - multidict=4.7.5=py37h9bfed18_1
  - multipledispatch=0.6.0=py_0
  - mysql-connector-c=6.1.11=had4075f_1006
  - mysqlclient=2.0.1=py37h570ac47_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.7=py_0
  - nbserverproxy=0.8.8=py_1000
  - ncurses=6.1=h0a44026_1002
  - netcdf4=1.5.4=nompi_py37h386ecc7_100
  - networkx=2.4=py_1
  - nodejs=13.13.0=h38d8c5a_0
  - nose=1.3.7=py37hc8dfbb8_1004
  - notebook=6.0.3=py37hc8dfbb8_1
  - numba=0.50.1=py37h0b113e5_1
  - numcodecs=0.6.4=py37h4a8c4bd_0
  - numexpr=2.7.1=py37h94625e5_1
  - numpy=1.19.1=py37h7e69742_0
  - oauth2client=4.1.3=py_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openjpeg=2.3.1=h254dc36_3
  - openpyxl=3.0.4=py_0
  - openssl=1.1.1g=h0b31af3_1
  - owslib=0.20.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pamela=1.0.0=py_0
  - pandas=1.1.0=py37hdadc0f0_0
  - pandoc=2.10.1=haf1e3a3_0
  - pandocfilters=1.4.2=py_1
  - panel=0.9.7=py_0
  - pango=1.40.14=h0da9b22_1005
  - param=1.9.3=py_0
  - paramiko=2.7.1=pyh9f0ad1d_1
  - parso=0.7.1=pyh9f0ad1d_0
  - partd=1.1.0=py_0
  - pathlib=1.0.1=py37hc8dfbb8_2
  - patsy=0.5.1=py_0
  - pcre=8.44=h4a8c4bd_0
  - peakutils=1.3.3=py_0
  - perl=5.26.2=haec8ef5_1006
  - petl=1.6.2=pyh9f0ad1d_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37hfd78ece_1
  - pip=20.2=py_0
  - pixman=0.38.0=h01d97ff_1003
  - pkg-config=0.29.2=hdc84dc8_1006
  - pomegranate=0.13.3=py37ha1cc60f_0
  - prettytable=0.7.2=py_3
  - proj=7.0.0=h45baca5_5
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.5=py_1
  - prompt_toolkit=3.0.5=1
  - protobuf=3.12.3=py37h570ac47_0
  - psutil=5.7.2=py37h60d8a13_0
  - pthread-stubs=0.4=h1de35cc_1001
  - ptyprocess=0.6.0=py_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pycurl=7.43.0.5=py37h7d0efee_2
  - pyepsg=0.4.0=py_0
  - pyfaidx=0.5.9=pyh864c0ab_1
  - pyfasta=0.5.2=py_1
  - pygments=2.6.1=py_0
  - pygraphviz=1.5=py37h9bfed18_1002
  - pyjwt=1.7.1=py_0
  - pykdtree=1.3.1=py37h10e2902_1003
  - pynacl=1.3.0=py37h0b31af3_1001
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=2.6.1.post1=py37hbd4ead9_0
  - pyprojroot=0.2.0=py_0
  - pyqt=5.9.2=py37h2a560b1_4
  - pyrsistent=0.16.0=py37h9bfed18_0
  - pysam=0.15.3=py37h726f235_1
  - pysamstats=1.1.2=py37h2573ce8_5
  - pysftp=0.2.9=py_1
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytables=3.6.1=py37he7827f7_2
  - python=3.7.6=cpython_h1fd5dd1_6
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python-graphviz=0.14.1=pyh9f0ad1d_0
  - python-irodsclient=0.8.2=py_0
  - python-kubernetes=11.0.0=py37hc8dfbb8_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyvcf=0.6.8=py37hc8dfbb8_1001
  - pyviz_comms=0.7.6=pyh9f0ad1d_0
  - pywavelets=1.1.1=py37h10e2902_1
  - pyyaml=5.3.1=py37h9bfed18_0
  - pyzmq=19.0.1=py37haec44b1_0
  - qt=5.9.7=h8cf7e54_3
  - qtconsole=4.7.5=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - ratelimiter=1.2.0=py37hc8dfbb8_1001
  - readline=8.0=hed1e85f_1
  - requests=2.24.0=pyh9f0ad1d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - s3fs=0.4.2=py_0
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - samtools=1.9=h8aa4d43_12
  - scikit-allel=1.3.1=py37h94625e5_0
  - scikit-image=0.17.2=py37h94625e5_1
  - scikit-learn=0.23.1=py37hf5857e7_0
  - scipy=1.5.2=py37h2702c91_0
  - seaborn=0.10.1=1
  - seaborn-base=0.10.1=py_1
  - send2trash=1.5.0=py_0
  - setuptools=49.2.0=py37hc8dfbb8_0
  - shapely=1.7.0=py37hfcf0db4_3
  - simplejson=3.17.2=py37h60d8a13_0
  - sip=4.19.8=py37h0a44026_1000
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.20.1=0
  - snakemake-minimal=5.20.1=py_0
  - snappy=1.1.8=h4a8c4bd_3
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sqlalchemy=1.3.18=py37h9bfed18_0
  - sqlite=3.32.3=h93121df_1
  - statsmodels=0.11.1=py37h9bfed18_2
  - svgwrite=1.4=py_2
  - tapi=1000.10.8=ha1b3eb9_4
  - tbb=2019.9=ha1b3eb9_1
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - thrift=0.11.0=py37h4a8c4bd_1001
  - tifffile=2020.7.24=py_0
  - tk=8.6.10=hbbe82c9_0
  - toolz=0.10.0=py_0
  - toposort=1.5=py_3
  - tornado=6.0.4=py37h9bfed18_1
  - tqdm=4.48.0=pyh9f0ad1d_0
  - traitlets=4.3.3=py37hc8dfbb8_1
  - traittypes=0.2.1=py_1
  - tskit=0.2.3=py37h3b54f70_0
  - typing_extensions=3.7.4.2=py_0
  - umap-learn=0.4.6=py37hc8dfbb8_0
  - uncertainties=3.1.4=py_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py37hc8dfbb8_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - wrapt=1.12.1=py37h9bfed18_1
  - xarray=0.16.0=py_0
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xlwt=1.3.0=py_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h1de35cc_1002
  - xorg-libice=1.0.10=h01d97ff_0
  - xorg-libsm=1.2.3=h01d97ff_1000
  - xorg-libx11=1.6.9=h0b31af3_0
  - xorg-libxau=1.0.9=h1de35cc_0
  - xorg-libxdmcp=1.1.3=h01d97ff_0
  - xorg-libxext=1.3.4=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-libxt=1.2.0=h01d97ff_0
  - xorg-renderproto=0.11.1=h1de35cc_1002
  - xorg-xextproto=7.3.0=h1de35cc_1002
  - xorg-xproto=7.0.31=h1de35cc_1007
  - xz=5.2.5=h0b31af3_1
  - yaml=0.2.5=h0b31af3_0
  - yarl=1.3.0=py37h0b31af3_1000
  - zarr=2.4.0=py_0
  - zeromq=4.3.2=h6de7cb9_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zstd=1.4.5=h0384e3a_2
  - pip:
    - alabaster==0.7.12
    - anhima==0.11.2
    - argcomplete==1.12.0
    - argh==0.26.2
    - babel==2.8.0
    - boto==2.49.0
    - cached-property==1.5.1
    - crcmod==1.7
    - gcs-oauth2-boto-plugin==2.6
    - google-apitools==0.5.31
    - google-reauth==0.1.0
    - gsutil==4.52
    - imagesize==1.2.0
    - livereload==2.6.2
    - mock==2.0.0
    - pathtools==0.1.2
    - pbr==5.4.5
    - petlx==1.0.3
    - port-for==0.3.1
    - prettypandas==0.0.4
    - pyerf==1.0.1
    - pyu2f==0.1.4
    - retry-decorator==1.1.1
    - scikits-bootstrap==1.0.1
    - snowballstemmer==2.0.0
    - socksipy-branch==1.1
    - sphinx==3.1.2
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.7.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - watchdog==0.10.3
